name: windows

on:
  push:
    tags:
      - v*
    paths-ignore:
      - README.md
      - examples/**
      - logo.png
      - logo_readme.png

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout latest sources
        uses: actions/checkout@v3
        with:
          path: re-latest-source
      
      - name: Checkout bootstrap sources
        uses: actions/checkout@v3
        with:
          ref: bootstrap
          path: re-bootstrap-source
          submodules: 'recursive'
          
      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            ./re-bootstrap-source/out/_deps
          key: ${{ runner.os }}-vcpkg-v1

      - name: Set up VsDevCmd
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Run the bootstrap script
        shell: pwsh
        run: ./re-latest-source/setup/bootstrap-re.ps1 -automated -arch x64 -main_src_dir ./re-latest-source
        #env:
        #  RE_GITHUB_FORCE_SSH: 1

      - name: Create CI artifact
        uses: actions/upload-artifact@v3
        with:
          name: re-${{ github.ref_name }}-windows-x64-${{ github.run_id }}
          path: ${{github.workspace}}/re-latest-build/
          
      - name: Archive release files
        uses: thedoctor0/zip-release@0.6.2
        with:
          type: zip
          filename: 're-${{ github.ref_name }}-windows-x64.zip'
          path: ${{github.workspace}}/re-latest-build/
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: 're-${{ github.ref_name }}-windows-x64.zip'
